dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

before_install:
  - pip install pytest pytest-cov pylint

install:
  - pip install .

cache: pip

# run tests
script:
  - pylint excode/
  - pylint test/*py
  - pylint tools/excode
  - cd test && pytest --cov excode

after_success:
  - bash <(curl -s https://codecov.io/bash)
