dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

before_install:
  - pip install pytest pytest-cov pylint

install:
  - pip install .

cache: pip

# run tests
script:
  - pylint code_extract/
  - pylint test/*py
  - pylint tools/code-extract
  - cd test && pytest --cov code_extract

after_success:
  - bash <(curl -s https://codecov.io/bash)
