version: 2

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y python3-pip git
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: pip3 install .
      # format and lint
      - black --check setup.py excode/ test/*.py tools/excode
      - flake8 setup.py excode/ test/*.py tools/excode
      # test
      - run: cd test/ && pytest --cov excode
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
